### ISSUE TITLE
Mise en place d'une classe de test sur une base vide

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-veloroutes_voies_vertes-plugin#10]
S'inspiré de https://github.com/3liz/qgis-gestion_base_adresse-plugin/pull/51

**Comment by rldhont** [comment]
@Gustry peux-tu mettre ça en place avec @Enola-sengeissen ?

L'idée est de pouvoir construire des tests autour des contraintes

**Comment by Gustry** [comment]
Oui, c'était dans ma roadmap justement.

J'ai activé Travis sur le dépôt.
@Enola-sengeissen Est-ce que tu regarder pour installer docker/docker-compose?

**Comment by Enola-sengeissen** [comment]
oui @Gustry je regarde ça

**Comment by Gustry** [comment]
* [ ] Copier/coller le `.docker`
* [ ] Adapter le `.env`
* [ ] Le Makefile copier/coller
* [ ] Dossier test
  * [ ] https://github.com/3liz/qgis-gestion_base_adresse-plugin/blob/master/gestion_base_adresse/test/base_test_database.py
  * [ ] https://github.com/3liz/qgis-gestion_base_adresse-plugin/blob/master/gestion_base_adresse/test/test_functions_without_data.py
