### ISSUE TITLE
Mettre la documentation de la base de données

### ISSUE THREAD

**Issue by Gustry** [3liz/qgis-veloroutes_voies_vertes-plugin#11]
Avant de faire #10, il semble plus simple de faire d’abord schemaspy

* [x] Copier/coller le .docker
* [x] Adapter le .env
* [x] Copier/coller le Makefile
* [x] Lancer schemaspy
* [x] Vérifier le fichier `index.html`
* [x] Mettre à jour le readme avec le lien https://3liz.github.io/qgis-veloroutes_voies_vertes-plugin/
* [x] Faire PR
* [x] Activer GitHub pages (pour @Gustry )

**Comment by Enola-sengeissen** [comment]
Super, avec toutes ces étapes ça a bien marché, j'ai ouvert un PR

**Comment by Gustry** [comment]
Merci ca marche
