### ISSUE TITLE
Tests des erreurs Python

### ISSUE THREAD

**Issue by Gustry** [3liz/qgis-veloroutes_voies_vertes-plugin#16]
* [x] Copier/coller le `setup.cfg`, la partie `flake8` et adapter
* [x] Copier coller la config `.github/workflows`
* [x] En local pour tester, `docker run --rm -w /plugin -v /home/etienne/dev/lizmap/lizmap-plugin/:/plugin etrimaille/flake8:3.8.2` à défaut d'avoir la commande `flake8` dans ton terminal

**Comment by Enola-sengeissen** [comment]
j'ai essayé la dernière commande j'ai :

`Status: Downloaded newer image for etrimaille/flake8:3.8.2
docker: Error response from daemon: Mounts denied: 
The path /home/etienne/dev/lizmap/lizmap-plugin
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.`

je regarde le lien là

**Comment by Gustry** [comment]
il faut modifier par le chemin sur ta machine, le `-v` vers le plugin : `-v /ton/chemin/vers/le/plugin/:/plugin`. C'est pour monter le répertoire dans le conteneur docker

**Comment by Enola-sengeissen** [comment]
ok merci ça fonctionne je vois les erreurs (majorité de too long) je vais corriger et voir ce qui reste

**Comment by Gustry** [comment]
C'est l'E501 ? https://github.com/3liz/lizmap-plugin/blob/master/setup.cfg#L13 Tu peux l'ajouter dans la liste des exceptions, ou alors augmenter la limite dans le cfg

**Comment by Enola-sengeissen** [comment]
Oui, ok je vais augmenter un peu

**Comment by Enola-sengeissen** [comment]
pblm j'ai ce type d'erreur : `E501 line too long (80 > 79 characters)` 
alors que dans le setup.cfg : `max-line-length = 105` 

c'est peut-être pas ici la limite de caractères?
