### ISSUE TITLE
Finaliser la CI pour sortir une première version

### ISSUE THREAD

**Issue by Gustry** [3liz/qgis-veloroutes_voies_vertes-plugin#18]
Avant de faire le tag:
* [x] Ajouter un .gitattributes et adapter
* [x] Ajouter le stage `deploy` de `.travis.yml`. Tu peux vérifier avec https://config.travis-ci.com/explore si jamais
* [x] Ajouter le fichier `.github/push_to_github.sh` et le rendre exécutable
* [x] Ajouter la config qgis-plugin-ci dans le `setup.cfg` et adapter
* [x] Ajouter un fichier CHANGELOG.md. Petit hack, ajouter une ligne à la fin par `###`
* [x] Faire le PR et on regarde le tag après

**Comment by Enola-sengeissen** [comment]
#19 

J'ai un doute lignes 4 et 5 du fichier push_to_github.sh
