### ISSUE TITLE
metadata table

### ISSUE THREAD

**Issue by Enola-sengeissen** [3liz/qgis-veloroutes_voies_vertes-plugin#22]
Voici mon problème :

L'algorithme upgrade_database_structure.py lis dans la table metadata de la bdd pour en connaitre la version.

Cette table n'existait pas dans ma structure je l'ai donc créée et ajouté les requêtes liées à sa création dans le fichier de migration. Je crois que ça coince car cette table n'est pas présente dès le départ. Elle apparaitrait en faisant un upgrade mais l'upgrade a besoin de la table metadata.

La solution est peut-être que je mette un if pour que si la table metadata n'existe pas alors on sait que la bdd est dans sa première version. @Gustry @rldhont

**Comment by Gustry** [comment]
Ah oui en effet, c'est un oubli.
Il faut l'ajouter dans les 2 fichiers 20 (prod et test)

**Comment by Enola-sengeissen** [comment]
on l'avait pas mis dans test hier sauf erreur de ma part 
c'est done : #24
