### ISSUE TITLE
comparaisons de text dans postgres

### ISSUE THREAD

**Issue by Enola-sengeissen** [3liz/qgis-veloroutes_voies_vertes-plugin#49]
Dans les fonctions d'import (cf 10_FUNCTION.sql : fonctions _import_veloroutes_xxx()_ et _insert_import_veloroutes_xxx()_
Des verifs sont faites, exemple : 
```
(EXISTS (SELECT 1 FROM veloroutes.portion_val WHERE code = type_portion)
		OR EXISTS (SELECT 1 FROM veloroutes.portion_val WHERE libelle = type_portion))
```
On veut verifier que la valeur d'un champs de type énuméré correspond bien au code ou au libelle de la table l'énumération correspondante. 

--> Utiliser upper() ou lower() pour être moins restrictif.

**Comment by drillinP** [comment]
Commit 50481bccd11c0ff196fc8cefdd171f4b783ef016
