### ISSUE TITLE
Ajouter un .gitignore

### ISSUE THREAD

**Issue by Gustry** [3liz/qgis-veloroutes_voies_vertes-plugin#6]
Dans le PR, il y a les fichiers .DS_STORE

```
*.DS_Store
.idea/
```

Cela évite que ces fichiers soient sur git

**Comment by Enola-sengeissen** [comment]
j'ai ajouté un .gitignore mais mon ordi ne veut pas créer de fichier démarrant par un "." donc je l'ai nommé "test" pour le moment...

**Comment by Gustry** [comment]
Avec un terminal, cela passe:
```bash
cd plugin
mv test.gitignore .gitignore
```

**Comment by Enola-sengeissen** [comment]
done
Le fichier ne s'affiche plus dans mon explorateur de fichiers mais je pense que c'est bon
