### ISSUE TITLE
Action: ajouter la sélection à une portion

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-veloroutes_voies_vertes-plugin#66]
Pour l'utilisateur, les étapes doivent être les suivantes : 
* Faire une sélection sur la couche **segment**
* Utiliser l'outil d'identifiaction sur la couche **v_portion**
* Choisir l'**action** : Ajouter les segments sélectionnés

Sur la couche **v_portion** : 
* Créer une **action python** à l'objet géographique
* Si le **nombre de segment sélectionnés** est inférieur à 1 afficher un message à l'utilisateur
* Sinon récupérer la valeur du champs **id_portion**
* Récupérer depuis la table **element** la liste des couples **(id_portion, id_segment)** correspondant
* Créer la liste des couples **(id_portion, id_segment)** de la sélection qui ne sont pas dans la table **element**
* Ajouter à la table **element** des nouveaux couples **(id_portion, id_segment)**
* Rafraichir la couche **v_portion**

**Comment by drillinP** [comment]
Commit c3cd5c7f4aa060984815643adaaa0f748037902a
