### ISSUE TITLE
Action: ajouter la sélection à un itinéraire

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-veloroutes_voies_vertes-plugin#67]
Pour l'utilisateur, les étapes doivent être les suivantes : 
* Faire une sélection sur la couche **v_portion**
* Utiliser l'outil d'identifiaction sur la couche **v_itineraire**
* Choisir l'**action** : Ajouter les portions sélectionnées

Sur la couche **v_itineraire** : 
* Créer une **action python** à l'objet géographique
* Si le **nombre de portions sélectionnées** est inférieur à 1 afficher un message à l'utilisateur
* Sinon récupérer la valeur du champs **id_iti**
* Récupérer depuis la table **etape** la liste des couples **(id_iti, id_portion)** correspondant
* Créer la liste des couples **(id_iti, id_portion)** de la sélection qui ne sont pas dans la table **etape**
* Ajouter à la table **etape** des nouveaux couples **(id_iti, id_portion)**
* Rafraichir la couche **v_itineraire**

**Comment by drillinP** [comment]
Commit c3cd5c7f4aa060984815643adaaa0f748037902a

**Comment by drillinP** [comment]
Commit c3cd5c7f4aa060984815643adaaa0f748037902a
