### ISSUE TITLE
Vérifier les formulaires des différentes couches

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-veloroutes_voies_vertes-plugin#75]
Des champs ont été ajoutés au modèle de données mais les formulaires n'ont pas forcément été mis à jour, il faut donc vérifier : 

- [ ] `v_portion`
  * `id_portion` : Hidden
  * `id_on3v`
  * `id_local`
  * `mont_subv` : Plage
  * `annee_subv` : Plage, minValue 2000
- [ ] `v_itineraire`
  * `id_iti` : Hidden
  * `numero`: Non null
  * `mont_subv` : Plage
  * `annee_subv` : Plage, minValue 2000

**Comment by drillinP** [comment]
@rldhont pour chacune des couche, la champ annee_subv QGIS me détecte les champ en date, donc le type Plage n'est pas attribuable

**Comment by rldhont** [comment]
OK, c'est peut-être une erreur de conception. Je vérifie le besoin.

**Comment by rldhont** [comment]
@drillinP je confirme que c'est une erreur dans le modèle de données. Il faut donc modifier la description des tables, les vues et les styles des couches et vues concernées:

* annee_subv int

**Comment by drillinP** [comment]
466771ff3c0c2a338fb9583e3879d66e3bc09a31

**Comment by drillinP** [comment]
Commit 466771ff3c0c2a338fb9583e3879d66e3bc09a31
