### ISSUE TITLE
Export: Utiliser directement les requêtes sans les tables exports

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-veloroutes_voies_vertes-plugin#80]
Dans la fonction [to_shapefile](https://github.com/3liz/qgis-veloroutes_voies_vertes-plugin/blob/master/veloroutes_voies_vertes/processing/covadis/export_covadis.py#L149) de l'algorithme [ExportCovadis](https://github.com/3liz/qgis-veloroutes_voies_vertes-plugin/blob/master/veloroutes_voies_vertes/processing/covadis/export_covadis.py) la couche qui va être exporté https://github.com/3liz/qgis-veloroutes_voies_vertes-plugin/blob/master/veloroutes_voies_vertes/processing/covadis/export_covadis.py#L151 s'appuie sur une table du schéma export. L'utilisation d'une table et du schéma export n'est pas nécessaire. Il est possible de créer une couche à partir d'une requête SQL.

- [x] Extraire les requêtes d'export dans des fichiers SQL dédiés
  - [ ] export_element
  - [ ] export_itineraire
  - [ ] export_liaison
  - [ ] export_poi_acces
  - [ ] export_poi_service
  - [ ] export_poi_tourisme
  - [ ] export_poi_portion
  - [ ] export_portion
  - [ ] export_repere
  - [ ] export_segment
- [x] Récupérer la requêtes SQL pour les autres tables
- [x] Le nom des champs en export doivent être en majuscule, donc adapter les SQL en conséquences
- [x] Modifier l'algorithme pour utiliser les requêtes SQL
- [x] Supprimer les fonctions extraites inutiles de la base de données

**Comment by drillinP** [comment]
Commit d4a2aaeec3c3ccbd81b3d5ffcc7906a7757e3b30
