### ISSUE TITLE
Charger le fichier plutôt que la couche 

### ISSUE THREAD

**Issue by drillinP** [3liz/qgis-veloroutes_voies_vertes-plugin#82]
Le paramètre `CHARGER` de l'algo **export_covadis**, 
https://github.com/3liz/qgis-veloroutes_voies_vertes-plugin/blob/86e7e3c42179dbcf241ff3c5e16076cc1e627e57/veloroutes_voies_vertes/processing/covadis/export_covadis.py#L125
signifie que l'on veut charger la couche correspondante à l'export dans le projet. Ne faut-il pas plutôt charger le fichier issu de l'export ?

**Comment by Gustry** [comment]
+1 pour moi.

Cela n'a pas de sens IMHO de vouloir recharger la table Postgres. (étant donné que l'on a déjà la couche dans la légende)

**Comment by rldhont** [comment]
D'après la ligne 130 'Si le traitement doit charger la couche Shapefile dans le projet'
https://github.com/3liz/qgis-veloroutes_voies_vertes-plugin/blob/86e7e3c42179dbcf241ff3c5e16076cc1e627e57/veloroutes_voies_vertes/processing/covadis/export_covadis.py#L130

Donc +1, maintenant la couche Postgres n'est pas forcément chargé dans le projet en cours.

**Comment by drillinP** [comment]
commit d4a2aaeec3c3ccbd81b3d5ffcc7906a7757e3b30
