### ISSUE TITLE
Problème nom de champs

### ISSUE THREAD

**Issue by drillinP** [3liz/qgis-veloroutes_voies_vertes-plugin#85]
etape --> id_tinéraire
itinéraire --> id_iti

Il faut la même nomenclature dans chaque table.

**Comment by rldhont** [comment]
@drillinP je pense que tu peux fermer cette demande et publier la version 0.4.1

**Comment by drillinP** [comment]
Commit d02b119b864febed02dfa1b245ce3bcaa56f6743
